<a href="https://colab.research.google.com/github/SkShoheb33/ComputationStatistics/blob/main/PricipleComponentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
n = int(input("Enter number of attributes : "))
x = []
for i in range(n):
  x.append(list(map(float,input().split())))


Enter number of attributes : 3
3 7  10 3 10
6 3 9 9 6
5 3 8 7 5


In [ ]:
X = np.array(x)
X = np.transpose(X)
meaw = np.mean(X,axis=0)
X_meaw = X- meaw
X_meaw

array([[-3.6, -0.6, -0.6],
       [ 0.4, -3.6, -2.6],
       [ 3.4,  2.4,  2.4],
       [-3.6,  2.4,  1.4],
       [ 3.4, -0.6, -0.6]])

In [ ]:
c = np.dot(np.transpose(X_meaw),X_meaw)/len(X)
eigenValues,eigenVectors = np.linalg.eig(c)
sort_id = eigenValues.argsort()[::-1]
eigenValues = eigenValues[sort_id]
eigenVectors = eigenVectors[:,sort_id]
eigenVectors = np.transpose(eigenVectors)
print(eigenValues,eigenVectors)

[9.87308342 8.00794009 0.03897648] [[-0.9982878   0.04206905 -0.04064073]
 [ 0.00841062  0.79080881  0.61200547]
 [-0.05788553 -0.61061578  0.78980861]]


In [ ]:
thresHold = int(input("Enter threshold percentage : "))

Enter threshold percentage : 95


In [ ]:
f = eigenValues[0]
s = sum(eigenValues)
k = [np.round((f/s)*100,2)]
count = 1
flag = 0
for i in range(1,n):
  f += eigenValues[i]
  k.append(np.round((f/s)*100,2))
  print(k,thresHold)
  if k[-1] <= thresHold or flag == 0:
    flag  = 1
    count += 1
dataFrame = {
    "Principle component" : ['z'+str(i+1) for i in range(n)],
    "Variance  explained" : eigenValues,
    "Cumulative proportion of total Vaiance " : k
}
pca_table = pd.DataFrame(dataFrame)
pca_table

[55.1, 99.78] 95
[55.1, 99.78, 100.0] 95


Principle component  Variance  explained  \
0                  z1             9.873083   
1                  z2             8.007940   
2                  z3             0.038976   

   Cumulative proportion of total Vaiance   
0                                    55.10  
1                                    99.78  
2                                   100.00

In [ ]:
count

2

In [ ]:
z = np.dot(eigenVectors[:count],X.T)
for i in range(len(z)):
  neg = 0
  for j in z[i]:
    if j<0:
      neg+=1
    if neg >= len(z[i])//2:
      z[i] = z[i]*(-1)
      break
x_ = X.T
result = {}
for i in range(len(x_)):
  result[f'x{i+1}'] = x_[i]
for i in range(len(z)):
  result[f'z{i+1}'] = z[i]

In [ ]:
table2 = pd.DataFrame(result)
table2

x1   x2   x3        z1         z2
0   3.0  6.0  5.0  2.945653   7.830112
1   7.0  3.0  3.0  6.983730   4.267317
2  10.0  9.0  8.0  9.929382  12.097429
3   3.0  9.0  7.0  2.900727  11.426549
4  10.0  6.0  5.0  9.933667   7.888986

In [ ]:
c = [[0.8,-0.0408,0.0643],[-0.0408,0.8,0.7848],[0.0643,0.7848,0.8]]
eigenValues,eigenVectors = np.linalg.eig(c)
eigenValues
eigenVectors

array([[-0.09347064, -0.99539514,  0.02125447],
       [-0.70331413,  0.08112344,  0.70623525],
       [ 0.70470737, -0.05106369,  0.70765812]])